// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Kanji is the predicate function for kanji builders.
type Kanji func(*sql.Selector)

// Radical is the predicate function for radical builders.
type Radical func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Vocabulary is the predicate function for vocabulary builders.
type Vocabulary func(*sql.Selector)
