version: "3.7"

x-kratos-common: &kratos-common
  image: oryd/kratos:v0.11.0
  environment:
    - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    - LOG_LEVEL=trace
  volumes:
    - type: bind
      source: ./auth-service/kratos
      target: /etc/config/kratos

services:
  postgres-kratos:
    image: postgres
    restart: unless-stopped
    networks:
      - intranet
    volumes:
      - kratos-postgres:/var/lib/postgresql/data

  kratos-migrate:
    <<: *kratos-common
    depends_on:
      - postgres-kratos
    restart: on-failure
    networks:
      - intranet

  kratos:
    <<: *kratos-common
    ports:
      - "4433:4433"
    depends_on:
      - kratos-migrate
    restart: unless-stopped
    networks:
      - intranet

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.11.0
    restart: on-failure
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    networks:
      - intranet

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
    restart: on-failure
    volumes:
      - type: bind
        source: ./auth-service/oathkeeper
        target: /etc/config/oathkeeper
    networks:
      - intranet

  postgres-manekani:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - manekani-postgres:/var/lib/postgresql/data
    networks:
      - intranet

  minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    command: server --console-address :${MINIO_PORT:-9001} /data
    volumes:
      - minio-data:/data
    networks:
      - intranet

  manekani:
    restart: unless-stopped
    depends_on:
      - minio
      - postgres-manekani
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /usr/src/manekani
    networks:
      - intranet

networks:
  intranet:

volumes:
  kratos-postgres:
  manekani-postgres:
  minio-data: