version: "3.7"

# THIS COMPOSE FILE IS MEANT FOR DEVELOPMENT.
# DON'T PUT ANY SENSITIVE DATA HERE!

services:
  postgres-kratos:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
  kratos-migrate:
    command: -c /etc/config/kratos/kratos.dev.yml migrate sql -e --yes
  kratos:
    ports:
      - "4433:4433"
      - "4434:4434"
    command: serve -c /etc/config/kratos/kratos.dev.yml --dev --watch-courier

  kratos-selfservice-ui-node:
    ports:
      - "4455:3000"
    environment:
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/

  mailslurper:
    ports:
      - "4436:4436"
      - "4437:4437"

  oathkeeper:
    ports:
      - "8080:4455"
      - "4456:4456"
    environment:
      - LOG_LEVEL=debug
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.dev.yml"

  postgres-manekani:
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=manekani
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=manekani

  minio:
    ports:
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  manekani:
    environment:
      - TOKEN_ENCRYPTION_KEY=cE0SC2E2A4qNoeCdlWo8vA218Uzqbnw4

      - S3_URL=minio:9000
      - AWS_ACCESS_KEY_ID=nVQ3bEvgakztwLHc
      - AWS_SECRET_ACCESS_KEY=BnjCq4zvkk6vwlLYeiq0uNfMTyIFdKQn

      - DB_URI=postgres://manekani:secret@postgres-manekani/manekani

      - MANEKANI_SERVER_PORT=10010
