version: "3.7"

# THIS COMPOSE FILE IS MEANT FOR DEVELOPMENT.
# DON'T PUT ANY SENSITIVE DATA HERE!

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=sixels
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=manekani
    volumes:
      - manekani-db:/var/lib/postgresql/data

  auth-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=sixels
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=supertokens
    volumes:
      - auth-db:/var/lib/postgresql/data
    networks:
      - auth

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    restart: always
    depends_on:
      - auth-db
    environment:
      - POSTGRESQL_CONNECTION_URI=postgresql://sixels:123@auth-db/supertokens
      - API_KEYS=60f98a9e-ce60-48c2-bfa2-8c4f623874af
    expose:
      - "3567"
    networks:
      - default
      - auth

  minio:
    image: quay.io/minio/minio:latest
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    expose:
      - "9000"
      - "9001"
    command: server --console-address ":9001" /data
    volumes:
      - minio-db:/data

  manekani:
    restart: unless-stopped
    depends_on:
      - minio
      - supertokens
      - postgres
    environment:
      - TOKEN_SIGN_KEY=iDBNNgcX3slubbIUQ5bEuHosTQVqDF2Z
      - TOKEN_ENCRYPTION_KEY=cE0SC2E2A4qNoeCdlWo8vA218Uzqbnw4

      - MANEKANI_S3_URL=minio:9000
      - AWS_ACCESS_KEY_ID=S6acsvuTta7QbL7k
      - AWS_SECRET_ACCESS_KEY=vlXDezn2NgrjQducm6aHrACl7FUKiO3W

      - MANEKANI_DB_URL=postgres://sixels:123@postgres/manekani

      - MANEKANI_AUTH_URL=http://supertokens:3567
      - MANEKANI_AUTH_SECRET=60f98a9e-ce60-48c2-bfa2-8c4f623874af

      # TODO: find a better way to define these values
      - MANEKANI_SERVER_URL=http://192.168.15.9
      - MANEKANI_SERVER_PORT=8081
      - MANEKANI_CLIENT_URL=http://192.168.15.9
      - MANEKANI_CLIENT_PORT=8082
    expose:
      - "8081"
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/usr/src/manekani

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - minio
      - supertokens
      - manekani
    volumes:
      # TODO: modularize nginx configuration
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
      - "3567:3567" # temporary
      - "8081:8081"

networks:
  default:
    name: "manekani-default-net"
  auth:
    name: "manekani-auth-net"

volumes:
  manekani-db:
    driver: local
  auth-db:
    driver: local
  minio-db:
    driver: local
