version: "3.7"

x-manekani-common: &manekani-common
  depends_on:
      - postgres-manekani
  build:
    context: ./
    dockerfile: ./docker/Dockerfile
  volumes:
    - type: bind
      source: ./
      target: /usr/src/manekani

services:
  minio:
    image: quay.io/minio/minio:latest
    restart: on-failure
    command: server --console-address :${MINIO_PORT:-9001} /data
    volumes:
      - minio-data:/data
    networks:
      - other

  ory-proxy:
    image: oryd/ory
    restart: on-failure
    depends_on:
      - manekani
    command: proxy --no-jwt --port 4001 http://manekani:3000/
    networks:
      - core
      - auth_infra

  manekani-migrate:
    <<: *manekani-common
    restart: on-failure
    networks:
      - core

  manekani:
    restart: on-failure
    depends_on:
      - minio
      - manekani-migrate
    build:
      context: ./
    volumes:
      - type: bind
        source: ./
        target: /usr/src/manekani
    networks:
      - core
      - auth_infra
      - other

  manekani-ui:
    restart: on-failure
    depends_on:
      - minio
      - manekani-migrate
    build:
      context: ./
    volumes:
      - type: bind
        source: ./
        target: /usr/src/manekani
    networks:
      - core
      - auth_infra
      - other

networks:
  core:
  auth_infra:
  other:

volumes:
  minio-data: