version: "3.7"

# THIS COMPOSE FILE IS MEANT FOR DEVELOPMENT.
# DON'T PUT ANY SENSITIVE DATA HERE!

services:
  postgres-kratos:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
  postgres-hydra:
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
  hydra-migrate:
    command: migrate -c /etc/config/hydra/hydra.dev.yml sql -e --yes
  hydra:
    command: serve all -c /etc/config/hydra/hydra.dev.yml --dev
    environment:
      - LOG_LEAK_SENSITIVE_VALUES=true
      - URLS_SELF_ISSUER=http://127.0.0.1:4444
      - URLS_SELF_PUBLIC=http://127.0.0.1:4444
      - URLS_CONSENT=http://127.0.0.1:3000/consent
      - URLS_LOGIN=http://127.0.0.1:3000/login
      - URLS_LOGOUT=http://127.0.0.1:3000/logout
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis
  kratos-migrate:
    command: migrate -c /etc/config/kratos/kratos.dev.yml sql -e --yes
  kratos:
    command: serve -c /etc/config/kratos/kratos.dev.yml --dev --watch-courier


  kratos-selfservice-ui-node:
    ports:
      - "3000:3000"
    environment:
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/

  mailslurper:
    ports:
      - "4436:4436"
      - "4437:4437"

  oathkeeper:
    ports:
      - "8080:4455"
      - "4456:4456"
    environment:
      - LOG_LEVEL=debug
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.dev.yml"

  postgres-manekani:
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=manekani
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=manekani

  minio:
    ports:
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  ory-proxy:
    ports:
      - "4001:4001"
    environment:
      - ORY_SDK_URL=http://kratos:4433

  manekani-migrate:
    user: 1000:1000
    env_file:
      - ./api/.env.development
    build:
      dockerfile: ./docker/Dockerfile.dev
      target: development-migrate
    command: "-- --name auto --create-only"

  manekani:
    user: 1000:1000
    ports:
      - "10011:3000"
    env_file:
      - ./api/.env.development
    build:
      dockerfile: ./docker/Dockerfile.dev
      target: development

  manekani-ui:
    user: 1000:1000
    ports:
      - "11011:11011"
    build:
      dockerfile: ./docker/Dockerfile.dev
      target: development-ui

    # environment:
      # - TOKEN_ENCRYPTION_KEY=cE0SC2E2A4qNoeCdlWo8vA218Uzqbnw4

      # - S3_URL=minio:9000
      # - AWS_ACCESS_KEY_ID=tIMp6AKWumjCiw2LoK9r
      # - AWS_SECRET_ACCESS_KEY=nvHwZgCv0ZUTT5zBUjdFiOIVbJFnG99AtbpoWyFi

      # - DB_URI=postgres://manekani:secret@postgres-manekani/manekani

      # - MANEKANI_SERVER_PORT=10010
