version: "2"

# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

    hostname: minio
    volumes:
      - minio-storage:/data

  nginx:
    image: nginx:alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  minio-storage:
    # driver: local
    # driver_opts:
    #   type: "none"
    #   o: "bind"
    #   device: "/home/sixels/.minio"
