version: "3"

# THIS COMPOSE FILE IS MEANT FOR DEVELOPMENT.
# DON'T PUT ANY SENSITIVE DATA HERE!

services:
  minio:
    image: minio/minio
    container_name: manekani-minio
    hostname: minio
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
    volumes:
      - /home/sixels/.manekani/minio:/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: manekani-keycloak
    hostname: keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: "9100"
      KC_DB: dev-file
      # KC_DB_PORT: "5433"
      # KC_DB_PASSWORD: "123"
      # KC_DB_USERNAME: adm_keycloak
      # KC_LOG: file
    ports:
      - "9100:9100"
    command: start-dev
    volumes:
      - /home/sixels/.manekani/keycloak:/data

  postgres:
    image: postgres:15-alpine
    container_name: manekani-postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: sixels
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: manekani
    ports:
      - "5432:5432"

  manekani:
    container_name: manekani-backend
    hostname: manekani
    restart: always
    environment:
      MANEKANI_DATA_HOME: /data
      MANEKANI_S3_URL: "minio:9000"
      MANEKANI_DB_URL: "postgres://sixels:123@postgres/manekani"
      AWS_ACCESS_KEY_ID: Kz31iB793qov0cTW
      AWS_SECRET_ACCESS_KEY: jKyin9lWVio2tCIDXu0JHr3a1zfcPQ78
      KEYCLOAK_CLIENT_ID: manekani-backend
      KEYCLOAK_CLIENT_SECRET: 3Wltkal8xnDTUSltry8LNxLpzdCarSsJ
      KEYCLOAK_URL: "http://keycloak:9100"
      KEYCLOAK_REALM: manekani
    # env_file:
    #   - ./backend/.env
    ports:
      - "8081:8081"
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - keycloak
      - minio
      - postgres
    volumes:
      - /home/sixels/.manekani:/data
      - ./backend:/app/manekani

  nginx:
    image: nginx:alpine
    container_name: manekani-nginx
    hostname: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
      - "8081:8081"
    depends_on:
      - minio
      - manekani
