services:
  postgres-manekani:
    image: postgres:16
    restart: on-failure
    volumes:
      - manekani-postgres:/var/lib/postgresql/data
    networks:
      - core

volumes:
  manekani-postgres:
