// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"sixels.io/manekani/ent/card"
	"sixels.io/manekani/ent/review"
)

// ReviewCreate is the builder for creating a Review entity.
type ReviewCreate struct {
	config
	mutation *ReviewMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (rc *ReviewCreate) SetCreatedAt(t time.Time) *ReviewCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *ReviewCreate) SetNillableCreatedAt(t *time.Time) *ReviewCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetMeaningErrors sets the "meaning_errors" field.
func (rc *ReviewCreate) SetMeaningErrors(i int) *ReviewCreate {
	rc.mutation.SetMeaningErrors(i)
	return rc
}

// SetNillableMeaningErrors sets the "meaning_errors" field if the given value is not nil.
func (rc *ReviewCreate) SetNillableMeaningErrors(i *int) *ReviewCreate {
	if i != nil {
		rc.SetMeaningErrors(*i)
	}
	return rc
}

// SetReadingErrors sets the "reading_errors" field.
func (rc *ReviewCreate) SetReadingErrors(i int) *ReviewCreate {
	rc.mutation.SetReadingErrors(i)
	return rc
}

// SetNillableReadingErrors sets the "reading_errors" field if the given value is not nil.
func (rc *ReviewCreate) SetNillableReadingErrors(i *int) *ReviewCreate {
	if i != nil {
		rc.SetReadingErrors(*i)
	}
	return rc
}

// SetStartProgress sets the "start_progress" field.
func (rc *ReviewCreate) SetStartProgress(u uint8) *ReviewCreate {
	rc.mutation.SetStartProgress(u)
	return rc
}

// SetEndProgress sets the "end_progress" field.
func (rc *ReviewCreate) SetEndProgress(u uint8) *ReviewCreate {
	rc.mutation.SetEndProgress(u)
	return rc
}

// SetID sets the "id" field.
func (rc *ReviewCreate) SetID(u uuid.UUID) *ReviewCreate {
	rc.mutation.SetID(u)
	return rc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (rc *ReviewCreate) SetNillableID(u *uuid.UUID) *ReviewCreate {
	if u != nil {
		rc.SetID(*u)
	}
	return rc
}

// SetCardID sets the "card" edge to the Card entity by ID.
func (rc *ReviewCreate) SetCardID(id uuid.UUID) *ReviewCreate {
	rc.mutation.SetCardID(id)
	return rc
}

// SetCard sets the "card" edge to the Card entity.
func (rc *ReviewCreate) SetCard(c *Card) *ReviewCreate {
	return rc.SetCardID(c.ID)
}

// Mutation returns the ReviewMutation object of the builder.
func (rc *ReviewCreate) Mutation() *ReviewMutation {
	return rc.mutation
}

// Save creates the Review in the database.
func (rc *ReviewCreate) Save(ctx context.Context) (*Review, error) {
	var (
		err  error
		node *Review
	)
	rc.defaults()
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ReviewMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, rc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Review)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ReviewMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ReviewCreate) SaveX(ctx context.Context) *Review {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ReviewCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ReviewCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *ReviewCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := review.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.MeaningErrors(); !ok {
		v := review.DefaultMeaningErrors
		rc.mutation.SetMeaningErrors(v)
	}
	if _, ok := rc.mutation.ReadingErrors(); !ok {
		v := review.DefaultReadingErrors
		rc.mutation.SetReadingErrors(v)
	}
	if _, ok := rc.mutation.ID(); !ok {
		v := review.DefaultID()
		rc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ReviewCreate) check() error {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Review.created_at"`)}
	}
	if _, ok := rc.mutation.MeaningErrors(); !ok {
		return &ValidationError{Name: "meaning_errors", err: errors.New(`ent: missing required field "Review.meaning_errors"`)}
	}
	if _, ok := rc.mutation.ReadingErrors(); !ok {
		return &ValidationError{Name: "reading_errors", err: errors.New(`ent: missing required field "Review.reading_errors"`)}
	}
	if _, ok := rc.mutation.StartProgress(); !ok {
		return &ValidationError{Name: "start_progress", err: errors.New(`ent: missing required field "Review.start_progress"`)}
	}
	if _, ok := rc.mutation.EndProgress(); !ok {
		return &ValidationError{Name: "end_progress", err: errors.New(`ent: missing required field "Review.end_progress"`)}
	}
	if _, ok := rc.mutation.CardID(); !ok {
		return &ValidationError{Name: "card", err: errors.New(`ent: missing required edge "Review.card"`)}
	}
	return nil
}

func (rc *ReviewCreate) sqlSave(ctx context.Context) (*Review, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (rc *ReviewCreate) createSpec() (*Review, *sqlgraph.CreateSpec) {
	var (
		_node = &Review{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: review.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: review.FieldID,
			},
		}
	)
	if id, ok := rc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(review.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.MeaningErrors(); ok {
		_spec.SetField(review.FieldMeaningErrors, field.TypeInt, value)
		_node.MeaningErrors = value
	}
	if value, ok := rc.mutation.ReadingErrors(); ok {
		_spec.SetField(review.FieldReadingErrors, field.TypeInt, value)
		_node.ReadingErrors = value
	}
	if value, ok := rc.mutation.StartProgress(); ok {
		_spec.SetField(review.FieldStartProgress, field.TypeUint8, value)
		_node.StartProgress = value
	}
	if value, ok := rc.mutation.EndProgress(); ok {
		_spec.SetField(review.FieldEndProgress, field.TypeUint8, value)
		_node.EndProgress = value
	}
	if nodes := rc.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   review.CardTable,
			Columns: []string{review.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: card.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.card_reviews = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReviewCreateBulk is the builder for creating many Review entities in bulk.
type ReviewCreateBulk struct {
	config
	builders []*ReviewCreate
}

// Save creates the Review entities in the database.
func (rcb *ReviewCreateBulk) Save(ctx context.Context) ([]*Review, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Review, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReviewMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ReviewCreateBulk) SaveX(ctx context.Context) []*Review {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ReviewCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ReviewCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
