version: '3.7'

services:
  postgres-manekani:
    image: postgres:15-alpine
    restart: on-failure
    volumes:
      - manekani-postgres:/var/lib/postgresql/data
    networks:
      - core

volumes:
  manekani-postgres: