openapi: 3.0.1
info:
  title: ManeKani API
  description: ManeKani API.
  # termsOfService: http://swagger.io/terms/
  # contact:
  #   name: API Support
  #   url: http://www.swagger.io/support
  #   email: sixels@protonmail.com
  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
  - url: http://127.0.0.1:8080
tags:
  - name: metric
    description: API health status
  - name: internal
    description: Internal API functionalities
  - name: subject
    description: Subjects API functionalities
  - name: deck
    description: Decks API functionalities
  - name: token
    description: Tokens API functionalities
  - name: user
    description: User related

# paths:
#   /health:
#     get:
#       tags:
#         - metric
#       summary: Check the health status of the server.
#       description: Check the health status of the server.
#       operationId: check-health
#       responses:
#         200:
#           description: OK
#           content:
#             application/json:
#               schema:
#                 type: object
#                 additionalProperties:
#                   type: object

components:
  schemas:
    common.Response:
      type: object
      required:
        - code
        - data
      properties:
        code:
          type: integer
        data:
          type: object

    common.ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string

  securitySchemes:
    ApiKey:
      type: apiKey
      description: API key authentication
      name: Authorization
      in: header
    Login:
      type: apiKey
      description:
        Login at http://127.0.0.1:4455/login and copy the contents of the
        'ory_kratos_session' cookie
      name: ory_kratos_session
      in: cookie
