x-kratos-common: &kratos-common
  image: oryd/kratos:v1.2.0
  environment:
    - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    - LOG_LEVEL=trace
  volumes:
    - type: bind
      source: ./infra/auth/config/kratos
      target: /etc/config/kratos

x-hydra-common: &hydra-common
  image: oryd/hydra:v2.1.1
  environment:
    - DSN=postgres://hydra:secret@postgres-hydra:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
  volumes:
    - type: bind
      source: ./infra/auth/config/hydra
      target: /etc/config/hydra

services:
  postgres-hydra:
    image: postgres
    restart: on-failure
    networks:
      - auth_infra
    volumes:
      - hydra-postgres:/var/lib/postgresql/data

  hydra-migrate:
    <<: *hydra-common
    depends_on:
      - postgres-hydra
    restart: on-failure
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    networks:
      - auth_infra

  hydra:
    <<: *hydra-common
    depends_on:
      - hydra-migrate
    ports:
      - "4444:4444" # public
      - "4445:4445" # admin
      - "5555:5555" # token user
    restart: on-failure
    command: serve all -c /etc/config/hydra/hydra.yml
    networks:
      - auth_infra

  postgres-kratos:
    image: postgres
    restart: on-failure
    networks:
      - auth_infra
    volumes:
      - kratos-postgres:/var/lib/postgresql/data

  kratos-migrate:
    <<: *kratos-common
    depends_on:
      - postgres-kratos
    restart: on-failure
    command: migrate -c /etc/config/kratos/kratos.yml sql -e --yes
    networks:
      - auth_infra

  kratos:
    <<: *kratos-common
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    depends_on:
      - kratos-migrate
    restart: on-failure
    command: serve -c /etc/config/kratos/kratos.yml
    networks:
      - auth_infra

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.2.0
    restart: on-failure
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_ADMIN_URL=http://kratos:4434
      - HYDRA_ADMIN_URL=http://hydra:4445
      - SECURITY_MODE=standalone
    networks:
      - auth_infra
      - core

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    networks:
      - auth_infra

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
    restart: on-failure
    volumes:
      - type: bind
        source: ./infra/auth/config/oathkeeper
        target: /etc/config/oathkeeper
    networks:
      - auth_infra

volumes:
  kratos-postgres:
  hydra-postgres:
