FROM node:20 as base

WORKDIR /usr/src/manekani

RUN corepack enable

COPY ./package.json ./yarn.lock ./

FROM base as development
RUN yarn install
EXPOSE 3000
CMD ["yarn", "workspace", "@manekani/api", "run", "start:dev"]

FROM base as development-ui
RUN yarn install
EXPOSE 11011
EXPOSE 11012
CMD ["yarn", "workspace", "@manekani/ui", "run", "start:dev"]

FROM base as development-migrate
RUN yarn install
ENTRYPOINT ["yarn", "workspace", "@manekani/api", "run", "migrate:dev"]

