// Code generated by ent, DO NOT EDIT.

package deckprogress

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/sixels/manekani/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldLTE(FieldID, id))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v uint32) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldEQ(FieldLevel, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v uint32) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v uint32) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...uint32) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...uint32) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v uint32) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v uint32) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v uint32) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v uint32) predicate.DeckProgress {
	return predicate.DeckProgress(sql.FieldLTE(FieldLevel, v))
}

// HasCards applies the HasEdge predicate on the "cards" edge.
func HasCards() predicate.DeckProgress {
	return predicate.DeckProgress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, CardsTable, CardsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCardsWith applies the HasEdge predicate on the "cards" edge with a given conditions (other predicates).
func HasCardsWith(preds ...predicate.Card) predicate.DeckProgress {
	return predicate.DeckProgress(func(s *sql.Selector) {
		step := newCardsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.DeckProgress {
	return predicate.DeckProgress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.DeckProgress {
	return predicate.DeckProgress(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeck applies the HasEdge predicate on the "deck" edge.
func HasDeck() predicate.DeckProgress {
	return predicate.DeckProgress(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeckTable, DeckColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeckWith applies the HasEdge predicate on the "deck" edge with a given conditions (other predicates).
func HasDeckWith(preds ...predicate.Deck) predicate.DeckProgress {
	return predicate.DeckProgress(func(s *sql.Selector) {
		step := newDeckStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeckProgress) predicate.DeckProgress {
	return predicate.DeckProgress(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeckProgress) predicate.DeckProgress {
	return predicate.DeckProgress(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeckProgress) predicate.DeckProgress {
	return predicate.DeckProgress(func(s *sql.Selector) {
		p(s.Not())
	})
}
