// Code generated by ent, DO NOT EDIT.

package ent

type AnyClient interface {
	ApiTokenClient() *ApiTokenClient
	CardClient() *CardClient
	DeckClient() *DeckClient
	DeckProgressClient() *DeckProgressClient
	ReviewClient() *ReviewClient
	SubjectClient() *SubjectClient
	UserClient() *UserClient
}

func (c *Client) ApiTokenClient() *ApiTokenClient {
	return c.ApiToken
}
func (c *Tx) ApiTokenClient() *ApiTokenClient {
	return c.ApiToken
}

func (c *Client) CardClient() *CardClient {
	return c.Card
}
func (c *Tx) CardClient() *CardClient {
	return c.Card
}

func (c *Client) DeckClient() *DeckClient {
	return c.Deck
}
func (c *Tx) DeckClient() *DeckClient {
	return c.Deck
}

func (c *Client) DeckProgressClient() *DeckProgressClient {
	return c.DeckProgress
}
func (c *Tx) DeckProgressClient() *DeckProgressClient {
	return c.DeckProgress
}

func (c *Client) ReviewClient() *ReviewClient {
	return c.Review
}
func (c *Tx) ReviewClient() *ReviewClient {
	return c.Review
}

func (c *Client) SubjectClient() *SubjectClient {
	return c.Subject
}
func (c *Tx) SubjectClient() *SubjectClient {
	return c.Subject
}

func (c *Client) UserClient() *UserClient {
	return c.User
}
func (c *Tx) UserClient() *UserClient {
	return c.User
}
