// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sixels/manekani/ent/card"
	"github.com/sixels/manekani/ent/deck"
	"github.com/sixels/manekani/ent/deckprogress"
	"github.com/sixels/manekani/ent/predicate"
	"github.com/sixels/manekani/ent/user"
)

// DeckProgressQuery is the builder for querying DeckProgress entities.
type DeckProgressQuery struct {
	config
	ctx        *QueryContext
	order      []deckprogress.OrderOption
	inters     []Interceptor
	predicates []predicate.DeckProgress
	withCards  *CardQuery
	withUser   *UserQuery
	withDeck   *DeckQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeckProgressQuery builder.
func (dpq *DeckProgressQuery) Where(ps ...predicate.DeckProgress) *DeckProgressQuery {
	dpq.predicates = append(dpq.predicates, ps...)
	return dpq
}

// Limit the number of records to be returned by this query.
func (dpq *DeckProgressQuery) Limit(limit int) *DeckProgressQuery {
	dpq.ctx.Limit = &limit
	return dpq
}

// Offset to start from.
func (dpq *DeckProgressQuery) Offset(offset int) *DeckProgressQuery {
	dpq.ctx.Offset = &offset
	return dpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dpq *DeckProgressQuery) Unique(unique bool) *DeckProgressQuery {
	dpq.ctx.Unique = &unique
	return dpq
}

// Order specifies how the records should be ordered.
func (dpq *DeckProgressQuery) Order(o ...deckprogress.OrderOption) *DeckProgressQuery {
	dpq.order = append(dpq.order, o...)
	return dpq
}

// QueryCards chains the current query on the "cards" edge.
func (dpq *DeckProgressQuery) QueryCards() *CardQuery {
	query := (&CardClient{config: dpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deckprogress.Table, deckprogress.FieldID, selector),
			sqlgraph.To(card.Table, card.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, deckprogress.CardsTable, deckprogress.CardsColumn),
		)
		fromU = sqlgraph.SetNeighbors(dpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (dpq *DeckProgressQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: dpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deckprogress.Table, deckprogress.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deckprogress.UserTable, deckprogress.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(dpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDeck chains the current query on the "deck" edge.
func (dpq *DeckProgressQuery) QueryDeck() *DeckQuery {
	query := (&DeckClient{config: dpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deckprogress.Table, deckprogress.FieldID, selector),
			sqlgraph.To(deck.Table, deck.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deckprogress.DeckTable, deckprogress.DeckColumn),
		)
		fromU = sqlgraph.SetNeighbors(dpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeckProgress entity from the query.
// Returns a *NotFoundError when no DeckProgress was found.
func (dpq *DeckProgressQuery) First(ctx context.Context) (*DeckProgress, error) {
	nodes, err := dpq.Limit(1).All(setContextOp(ctx, dpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deckprogress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dpq *DeckProgressQuery) FirstX(ctx context.Context) *DeckProgress {
	node, err := dpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeckProgress ID from the query.
// Returns a *NotFoundError when no DeckProgress ID was found.
func (dpq *DeckProgressQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dpq.Limit(1).IDs(setContextOp(ctx, dpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deckprogress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dpq *DeckProgressQuery) FirstIDX(ctx context.Context) int {
	id, err := dpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeckProgress entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeckProgress entity is found.
// Returns a *NotFoundError when no DeckProgress entities are found.
func (dpq *DeckProgressQuery) Only(ctx context.Context) (*DeckProgress, error) {
	nodes, err := dpq.Limit(2).All(setContextOp(ctx, dpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deckprogress.Label}
	default:
		return nil, &NotSingularError{deckprogress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dpq *DeckProgressQuery) OnlyX(ctx context.Context) *DeckProgress {
	node, err := dpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeckProgress ID in the query.
// Returns a *NotSingularError when more than one DeckProgress ID is found.
// Returns a *NotFoundError when no entities are found.
func (dpq *DeckProgressQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dpq.Limit(2).IDs(setContextOp(ctx, dpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deckprogress.Label}
	default:
		err = &NotSingularError{deckprogress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dpq *DeckProgressQuery) OnlyIDX(ctx context.Context) int {
	id, err := dpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeckProgresses.
func (dpq *DeckProgressQuery) All(ctx context.Context) ([]*DeckProgress, error) {
	ctx = setContextOp(ctx, dpq.ctx, "All")
	if err := dpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeckProgress, *DeckProgressQuery]()
	return withInterceptors[[]*DeckProgress](ctx, dpq, qr, dpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dpq *DeckProgressQuery) AllX(ctx context.Context) []*DeckProgress {
	nodes, err := dpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeckProgress IDs.
func (dpq *DeckProgressQuery) IDs(ctx context.Context) (ids []int, err error) {
	if dpq.ctx.Unique == nil && dpq.path != nil {
		dpq.Unique(true)
	}
	ctx = setContextOp(ctx, dpq.ctx, "IDs")
	if err = dpq.Select(deckprogress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dpq *DeckProgressQuery) IDsX(ctx context.Context) []int {
	ids, err := dpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dpq *DeckProgressQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dpq.ctx, "Count")
	if err := dpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dpq, querierCount[*DeckProgressQuery](), dpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dpq *DeckProgressQuery) CountX(ctx context.Context) int {
	count, err := dpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dpq *DeckProgressQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dpq.ctx, "Exist")
	switch _, err := dpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dpq *DeckProgressQuery) ExistX(ctx context.Context) bool {
	exist, err := dpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeckProgressQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dpq *DeckProgressQuery) Clone() *DeckProgressQuery {
	if dpq == nil {
		return nil
	}
	return &DeckProgressQuery{
		config:     dpq.config,
		ctx:        dpq.ctx.Clone(),
		order:      append([]deckprogress.OrderOption{}, dpq.order...),
		inters:     append([]Interceptor{}, dpq.inters...),
		predicates: append([]predicate.DeckProgress{}, dpq.predicates...),
		withCards:  dpq.withCards.Clone(),
		withUser:   dpq.withUser.Clone(),
		withDeck:   dpq.withDeck.Clone(),
		// clone intermediate query.
		sql:  dpq.sql.Clone(),
		path: dpq.path,
	}
}

// WithCards tells the query-builder to eager-load the nodes that are connected to
// the "cards" edge. The optional arguments are used to configure the query builder of the edge.
func (dpq *DeckProgressQuery) WithCards(opts ...func(*CardQuery)) *DeckProgressQuery {
	query := (&CardClient{config: dpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dpq.withCards = query
	return dpq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (dpq *DeckProgressQuery) WithUser(opts ...func(*UserQuery)) *DeckProgressQuery {
	query := (&UserClient{config: dpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dpq.withUser = query
	return dpq
}

// WithDeck tells the query-builder to eager-load the nodes that are connected to
// the "deck" edge. The optional arguments are used to configure the query builder of the edge.
func (dpq *DeckProgressQuery) WithDeck(opts ...func(*DeckQuery)) *DeckProgressQuery {
	query := (&DeckClient{config: dpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dpq.withDeck = query
	return dpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Level uint32 `json:"level,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeckProgress.Query().
//		GroupBy(deckprogress.FieldLevel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dpq *DeckProgressQuery) GroupBy(field string, fields ...string) *DeckProgressGroupBy {
	dpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeckProgressGroupBy{build: dpq}
	grbuild.flds = &dpq.ctx.Fields
	grbuild.label = deckprogress.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Level uint32 `json:"level,omitempty"`
//	}
//
//	client.DeckProgress.Query().
//		Select(deckprogress.FieldLevel).
//		Scan(ctx, &v)
func (dpq *DeckProgressQuery) Select(fields ...string) *DeckProgressSelect {
	dpq.ctx.Fields = append(dpq.ctx.Fields, fields...)
	sbuild := &DeckProgressSelect{DeckProgressQuery: dpq}
	sbuild.label = deckprogress.Label
	sbuild.flds, sbuild.scan = &dpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeckProgressSelect configured with the given aggregations.
func (dpq *DeckProgressQuery) Aggregate(fns ...AggregateFunc) *DeckProgressSelect {
	return dpq.Select().Aggregate(fns...)
}

func (dpq *DeckProgressQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dpq); err != nil {
				return err
			}
		}
	}
	for _, f := range dpq.ctx.Fields {
		if !deckprogress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dpq.path != nil {
		prev, err := dpq.path(ctx)
		if err != nil {
			return err
		}
		dpq.sql = prev
	}
	return nil
}

func (dpq *DeckProgressQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeckProgress, error) {
	var (
		nodes       = []*DeckProgress{}
		withFKs     = dpq.withFKs
		_spec       = dpq.querySpec()
		loadedTypes = [3]bool{
			dpq.withCards != nil,
			dpq.withUser != nil,
			dpq.withDeck != nil,
		}
	)
	if dpq.withUser != nil || dpq.withDeck != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, deckprogress.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeckProgress).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeckProgress{config: dpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dpq.withCards; query != nil {
		if err := dpq.loadCards(ctx, query, nodes,
			func(n *DeckProgress) { n.Edges.Cards = []*Card{} },
			func(n *DeckProgress, e *Card) { n.Edges.Cards = append(n.Edges.Cards, e) }); err != nil {
			return nil, err
		}
	}
	if query := dpq.withUser; query != nil {
		if err := dpq.loadUser(ctx, query, nodes, nil,
			func(n *DeckProgress, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := dpq.withDeck; query != nil {
		if err := dpq.loadDeck(ctx, query, nodes, nil,
			func(n *DeckProgress, e *Deck) { n.Edges.Deck = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dpq *DeckProgressQuery) loadCards(ctx context.Context, query *CardQuery, nodes []*DeckProgress, init func(*DeckProgress), assign func(*DeckProgress, *Card)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DeckProgress)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Card(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(deckprogress.CardsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.deck_progress_cards
		if fk == nil {
			return fmt.Errorf(`foreign-key "deck_progress_cards" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "deck_progress_cards" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (dpq *DeckProgressQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*DeckProgress, init func(*DeckProgress), assign func(*DeckProgress, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*DeckProgress)
	for i := range nodes {
		if nodes[i].user_decks_progress == nil {
			continue
		}
		fk := *nodes[i].user_decks_progress
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_decks_progress" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (dpq *DeckProgressQuery) loadDeck(ctx context.Context, query *DeckQuery, nodes []*DeckProgress, init func(*DeckProgress), assign func(*DeckProgress, *Deck)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DeckProgress)
	for i := range nodes {
		if nodes[i].deck_users_progress == nil {
			continue
		}
		fk := *nodes[i].deck_users_progress
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(deck.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "deck_users_progress" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dpq *DeckProgressQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dpq.querySpec()
	_spec.Node.Columns = dpq.ctx.Fields
	if len(dpq.ctx.Fields) > 0 {
		_spec.Unique = dpq.ctx.Unique != nil && *dpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dpq.driver, _spec)
}

func (dpq *DeckProgressQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deckprogress.Table, deckprogress.Columns, sqlgraph.NewFieldSpec(deckprogress.FieldID, field.TypeInt))
	_spec.From = dpq.sql
	if unique := dpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dpq.path != nil {
		_spec.Unique = true
	}
	if fields := dpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deckprogress.FieldID)
		for i := range fields {
			if fields[i] != deckprogress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dpq *DeckProgressQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dpq.driver.Dialect())
	t1 := builder.Table(deckprogress.Table)
	columns := dpq.ctx.Fields
	if len(columns) == 0 {
		columns = deckprogress.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dpq.sql != nil {
		selector = dpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dpq.ctx.Unique != nil && *dpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dpq.predicates {
		p(selector)
	}
	for _, p := range dpq.order {
		p(selector)
	}
	if offset := dpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeckProgressGroupBy is the group-by builder for DeckProgress entities.
type DeckProgressGroupBy struct {
	selector
	build *DeckProgressQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dpgb *DeckProgressGroupBy) Aggregate(fns ...AggregateFunc) *DeckProgressGroupBy {
	dpgb.fns = append(dpgb.fns, fns...)
	return dpgb
}

// Scan applies the selector query and scans the result into the given value.
func (dpgb *DeckProgressGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dpgb.build.ctx, "GroupBy")
	if err := dpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeckProgressQuery, *DeckProgressGroupBy](ctx, dpgb.build, dpgb, dpgb.build.inters, v)
}

func (dpgb *DeckProgressGroupBy) sqlScan(ctx context.Context, root *DeckProgressQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dpgb.fns))
	for _, fn := range dpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dpgb.flds)+len(dpgb.fns))
		for _, f := range *dpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeckProgressSelect is the builder for selecting fields of DeckProgress entities.
type DeckProgressSelect struct {
	*DeckProgressQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dps *DeckProgressSelect) Aggregate(fns ...AggregateFunc) *DeckProgressSelect {
	dps.fns = append(dps.fns, fns...)
	return dps
}

// Scan applies the selector query and scans the result into the given value.
func (dps *DeckProgressSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dps.ctx, "Select")
	if err := dps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeckProgressQuery, *DeckProgressSelect](ctx, dps.DeckProgressQuery, dps, dps.inters, v)
}

func (dps *DeckProgressSelect) sqlScan(ctx context.Context, root *DeckProgressQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dps.fns))
	for _, fn := range dps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
