import * as cookieParser from 'cookie-parser';

import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';

import { AppModule } from './app.module';
import { NestFactory } from '@nestjs/core';

// TODO: get this value from config/environment
const COOKIE_SECRETS = ['COOKIE_SIGN_SECRET'];

async function bootstrap() {
  const openapi = new DocumentBuilder()
    .setTitle('ManeKani API')
    .setDescription('ManeKani API')
    .setVersion('1.0')
    .addTag('subjects')
    .addTag('tokens')
    .addCookieAuth(
      'ory_kratos_session',
      {
        type: 'apiKey',
        description: 'Login cookie from Ory',
      },
      'Login',
    )
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        name: 'Authorization',
        in: 'header',
        description: 'Your API token generated by ManeKani',
      },
      'API Token',
    )
    .build();

  const app = await NestFactory.create(AppModule);

  app.use(cookieParser(COOKIE_SECRETS));

  const document = SwaggerModule.createDocument(app, openapi);
  SwaggerModule.setup('docs', app, document);

  await app.listen(3000);
}
bootstrap();
