// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ApiToken is the predicate function for apitoken builders.
type ApiToken func(*sql.Selector)

// Card is the predicate function for card builders.
type Card func(*sql.Selector)

// Deck is the predicate function for deck builders.
type Deck func(*sql.Selector)

// DeckProgress is the predicate function for deckprogress builders.
type DeckProgress func(*sql.Selector)

// Review is the predicate function for review builders.
type Review func(*sql.Selector)

// Subject is the predicate function for subject builders.
type Subject func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
